### ISSUE TITLE
Error parsing forward channel RangeError: port should be >= 0 and < 65536: NaN

### ISSUE THREAD

**Issue by pedrosanta** [share/livedb-mongo#18]
Hi there,

Hitting this bug. :(

```
Error parsing forward channel RangeError: port should be >= 0 and < 65536: NaN
    at Socket.connect (net.js:917:13)
    at Object.exports.connect.exports.createConnection (net.js:92:35)
    at Connection.start (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:173:29)
    at _connect (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:211:16)
    at ConnectionPool.start (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:231:3)
    at Server.connect (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:709:18)
    at Db.open (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/db.js:281:23)
    at connectFunction (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:275:67)
    at Function.MongoClient.connect (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:345:5)
    at SkinClass.SkinDb._open (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongoskin/lib/db.js:36:25)
    at SkinClass.open (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongoskin/lib/utils.js:162:14)
    at SkinClass.SkinCollection._open (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongoskin/lib/collection.js:49:17)
    at SkinClass.open (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongoskin/lib/utils.js:162:14)
    at SkinClass.(anonymous function) [as findOne] (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/node_modules/mongoskin/lib/utils.js:116:14)
    at LiveDbMongo.getSnapshot (/Users/pedrosanta/git/editor/node_modules/livedb-mongo/mongo.js:100:32)
    at Livedb._getSnapshot (/Users/pedrosanta/git/editor/node_modules/livedb/lib/index.js:613:21)
```

Using `livedb` 0.5.12 and `livedb-mongo` 0.4.1.

Any hints on what it might be?

Cheers.

**Comment by pedrosanta** [comment]
Sorry, my bad, bad Mongo URI because of bad config. :) Plainly stated on the error, port was NaN. Closing this.
